/*
 * This file is generated by jOOQ.
 */
package club.anims.surrellabot.database.model.tables;


import club.anims.surrellabot.database.model.DefaultSchema;
import club.anims.surrellabot.database.model.Keys;
import club.anims.surrellabot.database.model.tables.records.UsersRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row8;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Users extends TableImpl<UsersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>users</code>
     */
    public static final Users USERS = new Users();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UsersRecord> getRecordType() {
        return UsersRecord.class;
    }

    /**
     * The column <code>users.id</code>.
     */
    public final TableField<UsersRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>users.name</code>.
     */
    public final TableField<UsersRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>users.discord_id</code>.
     */
    public final TableField<UsersRecord, String> DISCORD_ID = createField(DSL.name("discord_id"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>users.guild_id</code>.
     */
    public final TableField<UsersRecord, String> GUILD_ID = createField(DSL.name("guild_id"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>users.has_admin_privileges</code>.
     */
    public final TableField<UsersRecord, Boolean> HAS_ADMIN_PRIVILEGES = createField(DSL.name("has_admin_privileges"), SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>users.has_mod_privileges</code>.
     */
    public final TableField<UsersRecord, Boolean> HAS_MOD_PRIVILEGES = createField(DSL.name("has_mod_privileges"), SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>users.is_blacklisted</code>.
     */
    public final TableField<UsersRecord, Boolean> IS_BLACKLISTED = createField(DSL.name("is_blacklisted"), SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>users.jail_channel_id</code>.
     */
    public final TableField<UsersRecord, String> JAIL_CHANNEL_ID = createField(DSL.name("jail_channel_id"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    private Users(Name alias, Table<UsersRecord> aliased) {
        this(alias, aliased, null);
    }

    private Users(Name alias, Table<UsersRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>users</code> table reference
     */
    public Users(String alias) {
        this(DSL.name(alias), USERS);
    }

    /**
     * Create an aliased <code>users</code> table reference
     */
    public Users(Name alias) {
        this(alias, USERS);
    }

    /**
     * Create a <code>users</code> table reference
     */
    public Users() {
        this(DSL.name("users"), null);
    }

    public <O extends Record> Users(Table<O> child, ForeignKey<O, UsersRecord> key) {
        super(child, key, USERS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Identity<UsersRecord, Integer> getIdentity() {
        return (Identity<UsersRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<UsersRecord> getPrimaryKey() {
        return Keys.USERS__;
    }

    @Override
    public Users as(String alias) {
        return new Users(DSL.name(alias), this);
    }

    @Override
    public Users as(Name alias) {
        return new Users(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Users rename(String name) {
        return new Users(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Users rename(Name name) {
        return new Users(name, null);
    }

    // -------------------------------------------------------------------------
    // Row8 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, String, String, String, Boolean, Boolean, Boolean, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }
}
