/*
 * This file is generated by jOOQ.
 */
package club.anims.surrellabot.database.model.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Guilds implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Integer       id;
    private final String        name;
    private final String        guildId;
    private final String        prefix;
    private final String        logChannelId;
    private final String        serverOwnerDiscordId;
    private final Boolean       isDisabled;
    private final LocalDateTime dateJoined;

    public Guilds(Guilds value) {
        this.id = value.id;
        this.name = value.name;
        this.guildId = value.guildId;
        this.prefix = value.prefix;
        this.logChannelId = value.logChannelId;
        this.serverOwnerDiscordId = value.serverOwnerDiscordId;
        this.isDisabled = value.isDisabled;
        this.dateJoined = value.dateJoined;
    }

    public Guilds(
        Integer       id,
        String        name,
        String        guildId,
        String        prefix,
        String        logChannelId,
        String        serverOwnerDiscordId,
        Boolean       isDisabled,
        LocalDateTime dateJoined
    ) {
        this.id = id;
        this.name = name;
        this.guildId = guildId;
        this.prefix = prefix;
        this.logChannelId = logChannelId;
        this.serverOwnerDiscordId = serverOwnerDiscordId;
        this.isDisabled = isDisabled;
        this.dateJoined = dateJoined;
    }

    /**
     * Getter for <code>guilds.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Getter for <code>guilds.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Getter for <code>guilds.guild_id</code>.
     */
    public String getGuildId() {
        return this.guildId;
    }

    /**
     * Getter for <code>guilds.prefix</code>.
     */
    public String getPrefix() {
        return this.prefix;
    }

    /**
     * Getter for <code>guilds.log_channel_id</code>.
     */
    public String getLogChannelId() {
        return this.logChannelId;
    }

    /**
     * Getter for <code>guilds.server_owner_discord_id</code>.
     */
    public String getServerOwnerDiscordId() {
        return this.serverOwnerDiscordId;
    }

    /**
     * Getter for <code>guilds.is_disabled</code>.
     */
    public Boolean getIsDisabled() {
        return this.isDisabled;
    }

    /**
     * Getter for <code>guilds.date_joined</code>.
     */
    public LocalDateTime getDateJoined() {
        return this.dateJoined;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Guilds (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(guildId);
        sb.append(", ").append(prefix);
        sb.append(", ").append(logChannelId);
        sb.append(", ").append(serverOwnerDiscordId);
        sb.append(", ").append(isDisabled);
        sb.append(", ").append(dateJoined);

        sb.append(")");
        return sb.toString();
    }
}
