/*
 * This file is generated by jOOQ.
 */
package club.anims.surrellabot.database.model.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Settings implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Integer id;
    private final String  name;
    private final String  value;

    public Settings(Settings value) {
        this.id = value.id;
        this.name = value.name;
        this.value = value.value;
    }

    public Settings(
        Integer id,
        String  name,
        String  value
    ) {
        this.id = id;
        this.name = name;
        this.value = value;
    }

    /**
     * Getter for <code>settings.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Getter for <code>settings.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Getter for <code>settings.value</code>.
     */
    public String getValue() {
        return this.value;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Settings (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(value);

        sb.append(")");
        return sb.toString();
    }
}
