/*
 * This file is generated by jOOQ.
 */
package club.anims.surrellabot.database.model.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SqliteSequence implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Object name;
    private final Object seq;

    public SqliteSequence(SqliteSequence value) {
        this.name = value.name;
        this.seq = value.seq;
    }

    public SqliteSequence(
        Object name,
        Object seq
    ) {
        this.name = name;
        this.seq = seq;
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public Object getName() {
        return this.name;
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public Object getSeq() {
        return this.seq;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SqliteSequence (");

        sb.append(name);
        sb.append(", ").append(seq);

        sb.append(")");
        return sb.toString();
    }
}
