/*
 * This file is generated by jOOQ.
 */
package club.anims.surrellabot.database.model.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Users implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Integer id;
    private final String  name;
    private final String  discordId;
    private final String  guildId;
    private final Boolean hasAdminPrivileges;
    private final Boolean hasModPrivileges;
    private final Boolean isBlacklisted;
    private final String  jailChannelId;

    public Users(Users value) {
        this.id = value.id;
        this.name = value.name;
        this.discordId = value.discordId;
        this.guildId = value.guildId;
        this.hasAdminPrivileges = value.hasAdminPrivileges;
        this.hasModPrivileges = value.hasModPrivileges;
        this.isBlacklisted = value.isBlacklisted;
        this.jailChannelId = value.jailChannelId;
    }

    public Users(
        Integer id,
        String  name,
        String  discordId,
        String  guildId,
        Boolean hasAdminPrivileges,
        Boolean hasModPrivileges,
        Boolean isBlacklisted,
        String  jailChannelId
    ) {
        this.id = id;
        this.name = name;
        this.discordId = discordId;
        this.guildId = guildId;
        this.hasAdminPrivileges = hasAdminPrivileges;
        this.hasModPrivileges = hasModPrivileges;
        this.isBlacklisted = isBlacklisted;
        this.jailChannelId = jailChannelId;
    }

    /**
     * Getter for <code>users.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Getter for <code>users.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Getter for <code>users.discord_id</code>.
     */
    public String getDiscordId() {
        return this.discordId;
    }

    /**
     * Getter for <code>users.guild_id</code>.
     */
    public String getGuildId() {
        return this.guildId;
    }

    /**
     * Getter for <code>users.has_admin_privileges</code>.
     */
    public Boolean getHasAdminPrivileges() {
        return this.hasAdminPrivileges;
    }

    /**
     * Getter for <code>users.has_mod_privileges</code>.
     */
    public Boolean getHasModPrivileges() {
        return this.hasModPrivileges;
    }

    /**
     * Getter for <code>users.is_blacklisted</code>.
     */
    public Boolean getIsBlacklisted() {
        return this.isBlacklisted;
    }

    /**
     * Getter for <code>users.jail_channel_id</code>.
     */
    public String getJailChannelId() {
        return this.jailChannelId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Users (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(discordId);
        sb.append(", ").append(guildId);
        sb.append(", ").append(hasAdminPrivileges);
        sb.append(", ").append(hasModPrivileges);
        sb.append(", ").append(isBlacklisted);
        sb.append(", ").append(jailChannelId);

        sb.append(")");
        return sb.toString();
    }
}
