/*
 * This file is generated by jOOQ.
 */
package club.anims.surrellabot.database.model.tables.records;


import club.anims.surrellabot.database.model.tables.Guilds;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GuildsRecord extends UpdatableRecordImpl<GuildsRecord> implements Record8<Integer, String, String, String, String, String, Boolean, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>guilds.id</code>.
     */
    public GuildsRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>guilds.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>guilds.name</code>.
     */
    public GuildsRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>guilds.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>guilds.guild_id</code>.
     */
    public GuildsRecord setGuildId(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>guilds.guild_id</code>.
     */
    public String getGuildId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>guilds.prefix</code>.
     */
    public GuildsRecord setPrefix(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>guilds.prefix</code>.
     */
    public String getPrefix() {
        return (String) get(3);
    }

    /**
     * Setter for <code>guilds.log_channel_id</code>.
     */
    public GuildsRecord setLogChannelId(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>guilds.log_channel_id</code>.
     */
    public String getLogChannelId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>guilds.server_owner_discord_id</code>.
     */
    public GuildsRecord setServerOwnerDiscordId(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>guilds.server_owner_discord_id</code>.
     */
    public String getServerOwnerDiscordId() {
        return (String) get(5);
    }

    /**
     * Setter for <code>guilds.is_disabled</code>.
     */
    public GuildsRecord setIsDisabled(Boolean value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>guilds.is_disabled</code>.
     */
    public Boolean getIsDisabled() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>guilds.date_joined</code>.
     */
    public GuildsRecord setDateJoined(LocalDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>guilds.date_joined</code>.
     */
    public LocalDateTime getDateJoined() {
        return (LocalDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, String, String, String, String, String, Boolean, LocalDateTime> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Integer, String, String, String, String, String, Boolean, LocalDateTime> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Guilds.GUILDS.ID;
    }

    @Override
    public Field<String> field2() {
        return Guilds.GUILDS.NAME;
    }

    @Override
    public Field<String> field3() {
        return Guilds.GUILDS.GUILD_ID;
    }

    @Override
    public Field<String> field4() {
        return Guilds.GUILDS.PREFIX;
    }

    @Override
    public Field<String> field5() {
        return Guilds.GUILDS.LOG_CHANNEL_ID;
    }

    @Override
    public Field<String> field6() {
        return Guilds.GUILDS.SERVER_OWNER_DISCORD_ID;
    }

    @Override
    public Field<Boolean> field7() {
        return Guilds.GUILDS.IS_DISABLED;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return Guilds.GUILDS.DATE_JOINED;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getGuildId();
    }

    @Override
    public String component4() {
        return getPrefix();
    }

    @Override
    public String component5() {
        return getLogChannelId();
    }

    @Override
    public String component6() {
        return getServerOwnerDiscordId();
    }

    @Override
    public Boolean component7() {
        return getIsDisabled();
    }

    @Override
    public LocalDateTime component8() {
        return getDateJoined();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getGuildId();
    }

    @Override
    public String value4() {
        return getPrefix();
    }

    @Override
    public String value5() {
        return getLogChannelId();
    }

    @Override
    public String value6() {
        return getServerOwnerDiscordId();
    }

    @Override
    public Boolean value7() {
        return getIsDisabled();
    }

    @Override
    public LocalDateTime value8() {
        return getDateJoined();
    }

    @Override
    public GuildsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public GuildsRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public GuildsRecord value3(String value) {
        setGuildId(value);
        return this;
    }

    @Override
    public GuildsRecord value4(String value) {
        setPrefix(value);
        return this;
    }

    @Override
    public GuildsRecord value5(String value) {
        setLogChannelId(value);
        return this;
    }

    @Override
    public GuildsRecord value6(String value) {
        setServerOwnerDiscordId(value);
        return this;
    }

    @Override
    public GuildsRecord value7(Boolean value) {
        setIsDisabled(value);
        return this;
    }

    @Override
    public GuildsRecord value8(LocalDateTime value) {
        setDateJoined(value);
        return this;
    }

    @Override
    public GuildsRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, Boolean value7, LocalDateTime value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GuildsRecord
     */
    public GuildsRecord() {
        super(Guilds.GUILDS);
    }

    /**
     * Create a detached, initialised GuildsRecord
     */
    public GuildsRecord(Integer id, String name, String guildId, String prefix, String logChannelId, String serverOwnerDiscordId, Boolean isDisabled, LocalDateTime dateJoined) {
        super(Guilds.GUILDS);

        setId(id);
        setName(name);
        setGuildId(guildId);
        setPrefix(prefix);
        setLogChannelId(logChannelId);
        setServerOwnerDiscordId(serverOwnerDiscordId);
        setIsDisabled(isDisabled);
        setDateJoined(dateJoined);
    }

    /**
     * Create a detached, initialised GuildsRecord
     */
    public GuildsRecord(club.anims.surrellabot.database.model.tables.pojos.Guilds value) {
        super(Guilds.GUILDS);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setGuildId(value.getGuildId());
            setPrefix(value.getPrefix());
            setLogChannelId(value.getLogChannelId());
            setServerOwnerDiscordId(value.getServerOwnerDiscordId());
            setIsDisabled(value.getIsDisabled());
            setDateJoined(value.getDateJoined());
        }
    }
}
