/*
 * This file is generated by jOOQ.
 */
package club.anims.surrellabot.database.model;


import club.anims.surrellabot.database.model.tables.Guilds;
import club.anims.surrellabot.database.model.tables.Settings;
import club.anims.surrellabot.database.model.tables.Users;
import club.anims.surrellabot.database.model.tables.records.GuildsRecord;
import club.anims.surrellabot.database.model.tables.records.SettingsRecord;
import club.anims.surrellabot.database.model.tables.records.UsersRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<GuildsRecord> GUILDS__ = Internal.createUniqueKey(Guilds.GUILDS, DSL.name(""), new TableField[] { Guilds.GUILDS.ID, Guilds.GUILDS.GUILD_ID }, true);
    public static final UniqueKey<SettingsRecord> SETTINGS__ = Internal.createUniqueKey(Settings.SETTINGS, DSL.name(""), new TableField[] { Settings.SETTINGS.ID, Settings.SETTINGS.NAME }, true);
    public static final UniqueKey<UsersRecord> USERS__ = Internal.createUniqueKey(Users.USERS, DSL.name(""), new TableField[] { Users.USERS.ID }, true);
}
