/*
 * This file is generated by jOOQ.
 */
package club.anims.surrellabot.database.model;


import club.anims.surrellabot.database.model.tables.Guilds;
import club.anims.surrellabot.database.model.tables.Settings;
import club.anims.surrellabot.database.model.tables.SqliteSequence;
import club.anims.surrellabot.database.model.tables.Users;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>guilds</code>.
     */
    public static final Guilds GUILDS = Guilds.GUILDS;

    /**
     * The table <code>settings</code>.
     */
    public static final Settings SETTINGS = Settings.SETTINGS;

    /**
     * The table <code>sqlite_sequence</code>.
     */
    public static final SqliteSequence SQLITE_SEQUENCE = SqliteSequence.SQLITE_SEQUENCE;

    /**
     * The table <code>users</code>.
     */
    public static final Users USERS = Users.USERS;
}
